language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install coveralls
  - pip install codacy-coverage
  - pip install pytest
script:
  - |
     coverage run --source=dffr -m pytest . -v && \
     coverage report && \
     coverage xml && \
     python-codacy-coverage -r coverage.xml
after_success:
  - coveralls
